name: Deploying A React App To Vultr

on:
    push:
        branches: [ main ]
    
jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: Try using SSH
          uses: appleboy/ssh-action@master
          with:
            host: 155.138.233.237
            username: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
                cd /var/www/actions
                git pull origin main
                export NVM_DIR="$HOME/.nvm"
                [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                nvm use v22.14.0
                npm install 
                npm run build
                systemctl reload nginx


